<aside class="col-3"><section class="shopping_list_menu"><div class="shopping_list_menu__block --lists slm_lists" data-empty="true"><span class="slm_lists__label">Listy zakupowe</span><ul class="slm_lists__nav"><li class="slm_lists__nav_item" data-list_skeleton="true" data-list_id="true" data-shared="true"><a class="slm_lists__nav_link" data-list_href="true"><span class="slm_lists__nav_name" data-list_name="true"></span><span class="slm_lists__count" data-list_count="true">0</span></a></li><li class="slm_lists__nav_header"><span class="slm_lists__label">Listy zakupowe</span></li><li class="slm_lists__nav_item --empty"><a class="slm_lists__nav_link --empty" href="https://www.konesso.pl/pl/shoppinglist/"><span class="slm_lists__nav_name" data-list_name="true">Lista zakupowa</span><span class="slm_lists__count" data-list_count="true">0</span></a></li></ul><a href="#manage" class="slm_lists__manage d-none align-items-center d-md-flex">Zarządzaj listami</a></div><div class="shopping_list_menu__block --bought slm_bought"><a class="slm_bought__link d-flex" href="https://www.konesso.pl/products-bought.php">
				Lista dotychczas zamówionych produktów
			</a></div><div class="shopping_list_menu__block --info slm_info"><strong class="slm_info__label d-block mb-3">Jak działa lista zakupowa?</strong><ul class="slm_info__list"><li class="slm_info__list_item d-flex mb-3">
					Po zalogowaniu możesz umieścić i przechowywać na liście zakupowej dowolną liczbę produktów nieskończenie długo.
				</li><li class="slm_info__list_item d-flex mb-3">
					Dodanie produktu do listy zakupowej nie oznacza automatycznie jego rezerwacji.
				</li><li class="slm_info__list_item d-flex mb-3">
					Dla niezalogowanych klientów lista zakupowa przechowywana jest do momentu wygaśnięcia sesji (około 24h).
				</li></ul></div></section><div id="mobileCategories" class="mobileCategories"><div class="mobileCategories__item --menu"><a class="mobileCategories__link --active" href="#" data-ids="#menu_search,.shopping_list_menu,#menu_search,#menu_navbar,#menu_navbar3, #menu_blog">
                            Menu
                        </a></div><div class="mobileCategories__item --account"><a class="mobileCategories__link" href="#" data-ids="#menu_contact,#login_menu_block">
                            Konto
                        </a></div></div><div class="setMobileGrid" data-item="#menu_navbar"></div><div class="setMobileGrid" data-item="#menu_navbar3" data-ismenu1="true"></div><div class="setMobileGrid" data-item="#menu_blog"></div><div class="login_menu_block d-lg-none" id="login_menu_block"><a class="your_account_link" href="/login.php" title=""><i class="icon-cog"></i><span>Twoje konto</span></a><a class="order_status_link" href="/order-open.php" title=""><i class="icon-globe"></i><span>Sprawdź status zamówienia</span></a><a class="client_card_link" href="https://www.konesso.pl/login.php"><i class="icon-barcode"></i><span>Identyfikator stałego klienta</span></a><a class="rabates_link" href="/client-rebate.php" title=""><span class="font_icon">%</span><span>Moje rabaty</span></a><a class="logout_link" href="/login.php?operation=logout" title=""><i class="icon-off" style="color: #CC0000;"></i><span>Wyloguj się</span></a></div><div class="setMobileGrid" data-item="#menu_contact"></div><div class="setMobileGrid" data-item="#menu_settings"></div><div class="setMobileGrid" data-item="#Filters"></div></aside>